#ifndef _VL53L0X_REGISTER_MAP_H_
#define _VL53L0X_REGISTER_MAP_H_

#define VL53L0X_REG_MSRC_CONFIG_TIMEOUT_MACROP             0x46
#define VL53L0X_REG_PRE_RANGE_CONFIG_TIMEOUT_MACROP_HI     0x51
#define VL53L0X_REG_FINAL_RANGE_CONFIG_TIMEOUT_MACROP_HI   0x71
#define VL53L0X_REG_PRE_RANGE_CONFIG_VALID_PHASE_HIGH      0x56
#define VL53L0X_REG_PRE_RANGE_CONFIG_VALID_PHASE_LOW       0x57
#define VL53L0X_REG_FINAL_RANGE_CONFIG_VALID_PHASE_HIGH    0x47
#define VL53L0X_REG_FINAL_RANGE_CONFIG_VALID_PHASE_LOW     0x48
#define VL53L0X_REG_GLOBAL_CONFIG_VCSEL_WIDTH              0x32
#define VL53L0X_REG_ALGO_PHASECAL_CONFIG_TIMEOUT           0x30
#define VL53L0X_REG_ALGO_PHASECAL_LIM                      0x3F
#define VL53L0X_REG_PRE_RANGE_CONFIG_VCSEL_PERIOD          0x50
#define VL53L0X_REG_FINAL_RANGE_CONFIG_VCSEL_PERIOD        0x70
#define VL53L0X_REG_SYSTEM_SEQUENCE_CONFIG                 0x01
#define VL53L0X_REG_ALGO_PART_TO_PART_RANGE_OFFSET_MM      0x28
#define VL53L0X_REG_RESULT_PEAK_SIGNAL_RATE_REF            0xB6
#define VL53L0X_REG_GLOBAL_CONFIG_SPAD_ENABLES_REF_0       0xB0
#define VL53L0X_REG_DYNAMIC_SPAD_REF_EN_START_OFFSET       0x4F
#define VL53L0X_REG_DYNAMIC_SPAD_NUM_REQUESTED_REF_SPAD    0x4E
#define VL53L0X_REG_POWER_MANAGEMENT_GO1_POWER_FORCE       0x80
#define VL53L0X_REG_SYSRANGE_START                         0x00
#define VL53L0X_REG_SYSRANGE_MODE_START_STOP               0x01
#define VL53L0X_REG_RESULT_INTERRUPT_STATUS                0x13  // Adresse correcte à confirmer dans datasheet
//#define VL53L0X_REG_SYSTEM_THRESH_LOW                      0x0C
#define VL53L0X_REG_SYSTEM_INTERRUPT_CLEAR                 0x0B
#define VL53L0X_REG_GPIO_HV_MUX_ACTIVE_HIGH                0x84
#define VL53L0X_REG_SYSTEM_INTERRUPT_CONFIG_GPIO           0x0A

#define VL53L0X_REG_RESULT_RANGE_STATUS                    0x14
//#define VL53L0X_REG_SYSRANGE_MODE_SINGLESHOT               0x00
//#define VL53L0X_GPIOFUNCTIONALITY_NEW_MEASURE_READY        0x0F

#define VL53L0X_REG_SYSTEM_INTERMEASUREMENT_PERIOD         0x04
#define VL53L0X_REG_CROSSTALK_COMPENSATION_PEAK_RATE_MCPS  0x20

//#define VL53L0X_REG_SYSTEM_INTERRUPT_GPIO_NEW_SAMPLE_READY 0x0B

#endif // _VL53L0X_REGISTER_MAP_H_




